server:
  port: 5000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/auth/**
            - id: location-service
              uri: lb://location-service
              predicates:
                - Path=/api/cities,/api/cities/**,/api/airports,/api/airports/**
            - id: airline-core-service
              uri: lb://airline-core-service
              predicates:
                - Path=/api/airlines,/api/airlines/**,/api/aircrafts,/api/aircrafts/**
            - id: pricing-service
              uri: lb://pricing-service
              predicates:
                - Path=/api/fares,/api/fares/**
            - id: ancillary-service
              uri: lb://ancillary-service
              predicates:
                - Path=/api/ancillaries,/api/ancillaries/**,/api/meals,/api/meals/**,/api/flight-ancillaries,/api/flight-ancillaries/**,/api/flight-meals,/api/flight-meals/**
            - id: seat-service
              uri: lb://seat-service
              predicates:
                - Path=/api/seat-instances,/api/seat-instances/**,/api/seat-maps,/api/seat-maps/**,/api/cabin-classes,/api/cabin-classes/**,/api/seats,/api/seats/**
            - id: flight-ops-service
              uri: lb://flight-ops-service
              predicates:
                - Path=/api/flights,/api/flights/**,/api/flight-instances,/api/flight-instances/**,/api/flight-schedules,/api/flight-schedules/**
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/api/bookings,/api/bookings/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments,/api/payments/**
