spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

notification:
  mail:
    from: noreply@airline-learn.local
